<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zfc607Snap\Module'                        => __DIR__ . '/Module.php',
    'Zfc607Snap\Controller\HomeController' => __DIR__ . '/src/Zfc607Snap/Controller/HomeController.php',
    'Zfc607SnapTest\Framework\TestCase'        => __DIR__ . '/tests/Zfc607Snap/Framework/TestCase.php',
    'Zfc607SnapTest\SampleTest'                => __DIR__ . '/tests/Zfc607Snap/SampleTest.php',
);
